# Generated by Django 3.0.2 on 2020-01-30 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_auto_20200130_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vaga', models.CharField(max_length=255, verbose_name='Título da vaga')),
                ('responsavel_vaga', models.CharField(max_length=255, verbose_name='Responsável pela vaga')),
                ('contato_secretaria', models.CharField(max_length=255, verbose_name='Contato da Secretaria')),
                ('area_vaga', models.CharField(max_length=255, verbose_name='Área da vaga')),
                ('telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('quantidade_vagas', models.IntegerField(verbose_name='Quantidade de Vagas')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('dias_trabalho', models.CharField(max_length=100)),
                ('horario_inicio', models.TimeField(verbose_name='Horário de início')),
                ('horario_final', models.TimeField(verbose_name='Horário de término')),
                ('beneficios', models.CharField(max_length=255, verbose_name='Quais os benefícios')),
                ('escolaridade', models.CharField(choices=[('EFI', 'Ensino fundamental incompleto'), ('CEF', 'Cursando ensino fundamental'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('CEM', 'Cursando ensino médio'), ('EMC', 'Ensino médio completo'), ('ESI', 'Ensino superior incompleto'), ('CES', 'Cursando ensino superior'), ('ESC', 'Ensino superior completo'), ('CT', 'Curso tecnico'), ('PGI', 'Pós graduação incompleto'), ('CPG', 'Cursando pós graduação'), ('PGC', 'Pós graduação complea')], max_length=6, verbose_name='Escolaridade mínima')),
                ('data_abertura', models.DateField(verbose_name='Data de abertura da vaga')),
                ('detalhes', models.TextField(verbose_name='Detalhes sobre a vaga')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.PessoaJuridica')),
            ],
        ),
    ]
