# Generated by Django 3.0.2 on 2020-01-30 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalhes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conhecimento_tecnico', models.CharField(max_length=255, verbose_name='Conhecimentos técnicos')),
                ('conhecimento_informatica', models.CharField(max_length=100, verbose_name='Conhecimento em informatica')),
                ('carregar_peso', models.BooleanField(choices=[('', ''), (True, 'Sim'), (False, 'Não')], default=False, verbose_name='Carregará peso ?')),
                ('peso', models.CharField(max_length=128, verbose_name='Quantos kgs em média?')),
                ('uso_escada', models.BooleanField(choices=[('', ''), (True, 'Sim'), (False, 'Não')], default=False, verbose_name='Fará uso constante da escada ?')),
                ('uso_elevador', models.BooleanField(choices=[('', ''), (True, 'Sim'), (False, 'Não')], default=False, verbose_name='Há elevador ou acessibilidade para modalidade ?')),
                ('tipo_atendimento', models.BooleanField(choices=[('', ''), (True, 'Sim'), (False, 'Não')], default=False, verbose_name='Há necessidade de atendimento ao público/cliente ? ')),
                ('postura_principal', models.CharField(choices=[('', ''), ('EP', 'Em pé'), ('SENTADO', 'Sentado'), ('DC', 'Deslocamento constante'), ('OUTRA', 'outra')], default=False, max_length=255, verbose_name='Qual forma de comunicação principal ?')),
                ('decisoes_complexas', models.BooleanField(choices=[('', ''), (True, 'Sim'), (False, 'Não')], default=False, verbose_name='Atividade exige concentração e tomadas de decisões complexas ?')),
                ('uso_ferramentas', models.CharField(max_length=255, verbose_name='Quais ferramentas ou equipamentos serão utilizados na atividade?')),
                ('uso_epi', models.CharField(max_length=255, verbose_name='Fará uso de EPI (Equipamento de Proteção Individual: Bota, protetor auricular, óculos de proteção, ect)? Quais ?')),
                ('acessibilidades', models.CharField(max_length=255, verbose_name='Quais recursos de acessibilidade empresa dispõe?')),
                ('adaptacoes', models.CharField(max_length=255, verbose_name='Há necessidade de apoio para adaptações para acessibilidade?')),
                ('data_entrevista', models.DateField(default=datetime.date.today, verbose_name='Data Prevista')),
                ('local_entrevista', models.CharField(max_length=255, verbose_name='Local da Entrevista')),
                ('termino_selecao', models.CharField(max_length=255, verbose_name='Previsão de término do processo seletivo')),
            ],
        ),
    ]
