# Generated by Django 2.2.9 on 2020-01-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoajuridica',
            old_name='ramo_ativiade',
            new_name='ramo_atividade',
        ),
    ]
