# Generated by Django 2.2.9 on 2020-01-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessibilidade',
            name='automovel',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Tem e faz uso de automóvel próprio?'),
        ),
        migrations.AddField(
            model_name='acessibilidade',
            name='autonomia_transporte',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Tem autonomia / independência para transporte público?'),
        ),
        migrations.AddField(
            model_name='acessibilidade',
            name='recursos',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Tem recursos financeiros para locomoção?'),
        ),
        migrations.AlterField(
            model_name='acessibilidade',
            name='cid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qual o CID ?'),
        ),
        migrations.AlterField(
            model_name='acessibilidade',
            name='outros_tipos_deficiencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='qual tipo?'),
        ),
        migrations.AlterField(
            model_name='acessibilidade',
            name='protese',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Faz uso de alguma órtese, prótese ou meios auxiliares de locomoção? (ex: cadeira de rodas, muleta, aparelho auditivo, etc'),
        ),
        migrations.AlterField(
            model_name='acessibilidade',
            name='restricao_fisica',
            field=models.BooleanField(blank=True, choices=[(True, 'Sim'), (False, 'Não')], default=False, null=True, verbose_name='Restrição para alguma atividade? Já teve adoecimento ou fastamento devido trabalho ou fora do trabalho? Acidente de trabalho anterior?'),
        ),
        migrations.AlterField(
            model_name='acessibilidade',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, choices=[('FISICA', 'Fisica'), ('AUDITIVA', 'Auditiva'), ('Visual', (('MONOCULAR', 'monocular'), ('TOTAL', 'total'), ('BAIXAVISAO', 'baixa visao'))), ('INTELECTUAL', 'Intelectual'), ('MULTIPLA', 'Multipla'), ('TEA', 'TEA'), ('TRANSTORNO MENTAL', 'Transtorno mental'), ('PSICOSOCIAL', 'Psicosocial'), ('OUTRA', 'Outra')], max_length=255, null=True, verbose_name='Qual sua deficiência ?'),
        ),
    ]
