# Generated by Django 3.0.2 on 2020-01-31 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao_Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_da_avaliacao', models.DateField(max_length=10, verbose_name='Data de avaliação')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('contratacao', models.DateField(max_length=10, verbose_name='Contratação')),
                ('cargo_funcao', models.CharField(max_length=255, verbose_name='Cargo / função')),
                ('atividade_realizada', models.CharField(max_length=255, verbose_name='Atividade Realizada')),
                ('adaptacao_local_de_trabalho', models.CharField(max_length=255, verbose_name='Adaptaçãp do local de trabalho')),
                ('atencao_limitacoes_habilidades', models.CharField(max_length=255, verbose_name='Atenção às minhas limitações e habilidades')),
                ('relacionamento_chefia', models.CharField(max_length=255, verbose_name='Relacionamento com Chefia')),
                ('relacionamento_colegas', models.CharField(max_length=255, verbose_name='Relacionamento com colegas')),
                ('nome_da_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.PessoaJuridica', verbose_name='Nome da empresa')),
                ('nome_do_trabalhador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.PessoaFisica', verbose_name='Nome do trabalhador')),
            ],
            options={
                'verbose_name': 'Avaliação da Secretaria',
            },
        ),
    ]
