# Generated by Django 3.0.2 on 2020-01-29 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_auto_20200128_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoajuridica',
            name='cnpj',
            field=models.CharField(max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='contato_empresa',
            field=models.CharField(max_length=14, verbose_name='Contato da empresa'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='nome_fantasia',
            field=models.CharField(max_length=255, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='numero_funcionarios',
            field=models.IntegerField(verbose_name='Numero de funcionarios'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='numero_pcds',
            field=models.IntegerField(verbose_name='Numero de pcds'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='ramo_atividade',
            field=models.CharField(max_length=255, verbose_name='Ramo de atividade'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão social'),
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=40)),
                ('cep', models.CharField(max_length=9)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Endereço',
            },
        ),
    ]
