# Generated by Django 2.2.9 on 2020-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200129_1205'),
        ('usuarios', '0002_auto_20200131_2148'),
    ]

    operations = [
    ]
