# Generated by Django 3.0.2 on 2020-01-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200129_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outros_tipos_deficiencia', models.CharField(max_length=255, verbose_name='qual tipo?')),
                ('tipo_deficiencia', models.CharField(choices=[('FISICA', 'Fisica'), ('AUDITIVA', 'Auditiva'), ('Visual', (('MONOCULAR', 'monocular'), ('TOTAL', 'total'), ('BAIXAVISAO', 'baixa visao'))), ('INTELECTUAL', 'Intelectual'), ('MULTIPLA', 'Multipla'), ('TEA', 'TEA'), ('TRANSTORNO MENTAL', 'Transtorno mental'), ('PSICOSOCIAL', 'psicosocial'), ('OUTRA. QUAL ?', 'Outra. Qual?')], max_length=255, verbose_name='Qual sua defic,iencia ?')),
                ('cid', models.CharField(max_length=255, verbose_name='Qual o CID ?')),
                ('protese', models.BooleanField(choices=[('TRUE', 'Sim'), ('FALSE', 'NAO')], default=False, verbose_name='Faz uso de alguma órtese, prótese ou meios auxiliares de locomoção? (ex: cadeira de rodas, muleta, aparelho auditivo, etc')),
                ('restricao_fisica', models.BooleanField(choices=[('TRUE', 'Sim'), ('FALSE', 'NAO')], default=False, verbose_name='Restrição para alguma atividade? Já teve adoecimento ou fastamento devido trabalho ou fora do trabalho? Acidente de trabalho anterior? (Demais riscos ou limitações observados pelo entrevistador)')),
                ('tecnologia', models.BooleanField(choices=[('TRUE', 'Sim'), ('FALSE', 'NAO')], default=False, verbose_name='Necessita de Tecnologia Assistiva para o Trabalho? Qual?')),
            ],
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=40),
        ),
    ]
