# Generated by Django 2.2.9 on 2020-02-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200204_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessibilidade',
            name='pessoa_fisica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.PessoaFisica', verbose_name='Pessoa fisica'),
            preserve_default=False,
        ),
    ]
