# Generated by Django 3.0.2 on 2020-02-05 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200204_1731'),
        ('usuarios', '0003_auto_20200204_1151'),
    ]

    operations = [
    ]
