# Generated by Django 3.0.2 on 2020-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200129_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outros_tipos_deficiencia', models.CharField(max_length=255, verbose_name='qual tipo?')),
                ('tipo_deficiencia', models.CharField(choices=[('FISICA', 'Fisica'), ('AUDITIVA', 'Auditiva'), ('Visual', (('MONOCULAR', 'monocular'), ('TOTAL', 'total'), ('BAIXAVISAO', 'baixa visao'))), ('INTELECTUAL', 'Intelectual'), ('MULTIPLA', 'Multipla'), ('TEA', 'TEA'), ('TRANSTORNO MENTAL', 'Transtorno mental'), ('PSICOSOCIAL', 'Psicosocial'), ('OUTRA', 'Outra')], max_length=255, verbose_name='Qual sua deficiência ?')),
                ('cid', models.CharField(max_length=255, verbose_name='Qual o CID ?')),
                ('protese', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Faz uso de alguma órtese, prótese ou meios auxiliares de locomoção? (ex: cadeira de rodas, muleta, aparelho auditivo, etc')),
                ('restricao_fisica', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Restrição para alguma atividade? Já teve adoecimento ou fastamento devido trabalho ou fora do trabalho? Acidente de trabalho anterior? (Demais riscos ou limitações observados pelo entrevistador)')),
                ('tecnologia', models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Necessita de Tecnologia Assistiva para o Trabalho? Qual?')),
            ],
            options={
                'verbose_name': 'Acessibilidade',
            },
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='nome_fantasia',
            field=models.CharField(max_length=255, verbose_name='Nome fantasia da empresa'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='numero_funcionarios',
            field=models.IntegerField(verbose_name='Número de funcionários'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='numero_pcds',
            field=models.IntegerField(verbose_name='Número de PCDs'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='razao_social',
            field=models.CharField(max_length=255, verbose_name='Razão social da empresa'),
        ),
    ]
