# Generated by Django 3.0.2 on 2020-01-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200130_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao_secretaria',
            name='contracao',
        ),
        migrations.AddField(
            model_name='avaliacao_secretaria',
            name='adaptacao_local_de_trabalho',
            field=models.CharField(default=23, max_length=255, verbose_name='Adaptaçãp do local de trabalho'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao_secretaria',
            name='atencao_limitacoes_habilidades',
            field=models.CharField(default=23, max_length=255, verbose_name='Atenção às minhas limitações e habilidades'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao_secretaria',
            name='atividade_realizada',
            field=models.CharField(default=23, max_length=255, verbose_name='Atividade Realizada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao_secretaria',
            name='contratacao',
            field=models.DateField(default=23, max_length=10, verbose_name='Contratação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao_secretaria',
            name='relacionamento_chefia',
            field=models.CharField(default=23, max_length=255, verbose_name='Relacionamento com Chefia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avaliacao_secretaria',
            name='relacionamento_colegas',
            field=models.CharField(default=23, max_length=255, verbose_name='Relacionamento com colegas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(default=23, max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='criado_em',
            field=models.DateField(auto_now=True, verbose_name='Criado'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='data_nascimento',
            field=models.DateField(default=34, max_length=10, verbose_name='Nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='estado_civil',
            field=models.CharField(choices=[('ESCOLHA O ESTADO CIVIL', 'Escolha o estado Civil'), ('SOLTEIRO(A)', 'Solteiro(a)'), ('CASADO(A)', 'Casado(a)'), ('DIVORCIADO(A)', 'Divociado(a)'), ('VIÙVO(A)', 'Viúvo(a)')], default=True, max_length=255, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='genero',
            field=models.CharField(choices=[('ESCOLHA O GÊNERO', 'Escolha o gênero'), ('MASCOLINO', 'Mascolino'), ('FEMININO', 'Feminino'), ('NÃO BINÁRIO', 'Não Binário'), ('OUTROS', 'Outros')], default=False, max_length=255, verbose_name='Genêro'),
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='nome',
            field=models.CharField(default=23, max_length=255, verbose_name='Nome:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='numero',
            field=models.CharField(default=23, max_length=13, verbose_name='Numero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='telefone',
            field=models.CharField(choices=[('FIXO', 'Fixo'), ('CELULAR', 'Celular')], default=True, max_length=13, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='avaliacao_secretaria',
            name='cargo_funcao',
            field=models.CharField(max_length=255, verbose_name='Cargo / função'),
        ),
        migrations.AlterField(
            model_name='avaliacao_secretaria',
            name='data_da_avaliacao',
            field=models.DateField(max_length=10, verbose_name='Data de avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliacao_secretaria',
            name='nome_da_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.PessoaJuridica', verbose_name='Nome da empresa'),
        ),
        migrations.AlterField(
            model_name='avaliacao_secretaria',
            name='nome_do_trabalhador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.PessoaFisica', verbose_name='Nome do trabalhador'),
        ),
        migrations.AlterField(
            model_name='avaliacao_secretaria',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=40),
        ),
    ]
