# Generated by Django 2.2.9 on 2020-02-07 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_acessibilidade_pessoa_fisica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255, verbose_name='Objetivos')),
                ('qualificacao_profissional', models.CharField(max_length=255, null=True, verbose_name='Qualificação Profissional')),
                ('pretensao_salarial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escolaridade', models.CharField(choices=[('EFI', 'Ensino fundamental incompleto'), ('CEF', 'Cursando ensino fundamental'), ('EFC', 'Ensino fundamental completo'), ('EMI', 'Ensino médio incompleto'), ('CEM', 'Cursando ensino médio'), ('EMC', 'Ensino médio completo'), ('ESI', 'Ensino superior incompleto'), ('CES', 'Cursando ensino superior'), ('ESC', 'Ensino superior completo'), ('CT', 'Curso tecnico'), ('PGI', 'Pós graduação incompleto'), ('CPG', 'Cursando pós graduação'), ('PGC', 'Pós graduação completa')], max_length=128, verbose_name='Escolaridade')),
                ('curso', models.CharField(max_length=100, verbose_name='Qual o curso')),
                ('instituicao_ensino', models.CharField(max_length=255, verbose_name='Instituição que realizou o curso')),
                ('ano_inicio', models.DateField(verbose_name='Ano de inicio')),
                ('ano_termino', models.DateField(verbose_name='Ano de termino')),
                ('cursos_extras', models.CharField(max_length=255, verbose_name='Cursos extras')),
                ('nivel_de_leitura', models.CharField(choices=[('NA', 'Não alfabetizado'), ('B', 'Básico (textos simples)'), ('LEA', 'Leitura e escrita avaçada (sem dificuldades)')], max_length=100, verbose_name='Nivel de leitura')),
                ('nivel_informatica', models.CharField(max_length=255)),
                ('word_nivel', models.CharField(choices=[('NA', 'Não alfabetizado'), ('B', 'Básico (textos simples)'), ('LEA', 'Leitura e escrita avaçada (sem dificuldades)')], max_length=100, verbose_name='Word')),
                ('excel_nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado'), ('NT', 'Não tenho')], max_length=100, verbose_name='Excel')),
                ('pptx_nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado'), ('NT', 'Não tenho')], max_length=100, verbose_name='Power Point')),
                ('internet_nivel', models.CharField(choices=[('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado'), ('NT', 'Não tenho')], max_length=100, verbose_name='Internet')),
                ('lingua', models.CharField(max_length=255, verbose_name='Linguas estrangeiras')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.PessoaFisica')),
            ],
            options={
                'verbose_name': 'Competência',
            },
        ),
    ]
