# Generated by Django 3.0.2 on 2020-02-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=255, verbose_name='Objetivos')),
                ('qualificacao_profisssional', models.TextField(verbose_name='Qualificação profissional')),
                ('prentencao_salarial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escolaridade', models.CharField(choices=[('EFI', 'Ensino Fundamental Inconpleto'), ('EFC', 'Ensino Fundamental Completo'), ('EFCu', 'Ensino FUndamental Cursando'), ('EMI', 'Ensino Médio Incompleto'), ('EMC', 'Ensino Médio Completo'), ('EMCu', 'Ensino Médio Cursando'), ('CT', 'Curso Técnico'), ('ESI', 'Ensino Superior Incompleto'), ('ESC', 'Ensino Superior Completo'), ('ESCu', 'Ensino Superior Cursando'), ('PGI', 'Pós graduação Inconcpleto'), ('PGC', 'Pós Graduação Completo'), ('PGCu', 'Pós Graduação Cursando')], max_length=128, verbose_name='Escolaridade')),
                ('qual_curso', models.CharField(max_length=100, verbose_name='Qual o curso')),
                ('instituicao_ensino_curso', models.CharField(max_length=255, verbose_name='Instituição que realizou o curso')),
                ('ano_inicio', models.DateField(verbose_name='Ano de inicio')),
                ('ano_termino', models.DateField(verbose_name='Ano de termino')),
                ('cursos_extras', models.CharField(max_length=255, verbose_name='Cursos extras')),
                ('nivel_de_leitura', models.CharField(choices=[('NA', 'Não alfabetizado'), ('B', 'Básico (textos simples)'), ('LEA', 'Leitura e escrita avaçada (sem dificuldades)')], max_length=100, verbose_name='Nivel de leitura')),
                ('nivel_informatica', models.CharField(choices=[('Word', (('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado'), ('NT', 'Não tenho'))), ('Excel', (('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado'), ('NT', 'Não tenho'))), ('PowerPoint', (('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado'), ('NT', 'Não tenho'))), ('Internet', (('B', 'Básico'), ('I', 'Intermediario'), ('A', 'Avançado'), ('NT', 'Não tenho')))], max_length=100, verbose_name='Nivel de informatica')),
                ('lingua_estrangeira', models.BooleanField(verbose_name='Lingua Estrangeira')),
                ('lingua', models.TextField()),
            ],
            options={
                'verbose_name': 'Competência',
            },
        ),
    ]
