# Generated by Django 3.0.2 on 2020-02-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competencia',
            old_name='prentencao_salarial',
            new_name='pretencao_salarial',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='qualificacao_profisssional',
        ),
        migrations.AddField(
            model_name='competencia',
            name='qualificacao_profissional',
            field=models.CharField(max_length=255, null=True, verbose_name='Qualificação Profissional'),
        ),
    ]
